### ISSUE TITLE
_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DDC0CBB048>: attribute lookup <lambda> on __main__ failed

### ISSUE THREAD

**Issue by Yukuncn** [lyhue1991/eat_pytorch_in_20_days#15]
in1-2 code:
 for x,y in dl_trian:
       print(x.shape,y.shape)
         break
error:_pickle.PicklingError: Can't pickle <function <lambda> at 0x000002DDC0CBB048>: attribute lookup <lambda> on __main__ failed.
because the error the whole code can run correctly

**Comment by BestRvienNa** [comment]
my os :windows 10

**Comment by strawberry2333** [comment]
我也是，会不会是torch版本问题？实在不知怎么解决。

**Comment by hadisi1993** [comment]
我也是，有人知道怎么解决吗

**Comment by hadisi1993** [comment]
issue当中有解决方法
