### ISSUE TITLE
torchkeras里面没有LightModel了吗？

### ISSUE THREAD

**Issue by AnthonyK97** [lyhue1991/eat_pytorch_in_20_days#19]
`
class Model(torchkeras.LightModel):
`
AttributeError: module 'torchkeras' has no attribute 'LightModel'

**Comment by hitergelei** [comment]
我也遇到了这个问题，试试命令升级下torchkeras版本：```!pip install -U torchkeras ```，我的是这么解决了。

**Comment by hitergelei** [comment]
> `class Model(torchkeras.LightModel):`
> AttributeError: module 'torchkeras' has no attribute 'LightModel'

我也遇到了这个问题，试试命令升级下torchkeras版本：```!pip install -U torchkeras``` ，我的是这么解决了。

**Comment by AnthonyK97** [comment]
👌Thanks♪(･ω･)ﾉ
