### ISSUE TITLE
能否修改每篇的代码,删除torchkeras这个库的代码

### ISSUE THREAD

**Issue by xiayutong** [lyhue1991/eat_pytorch_in_20_days#7]
我是来学习pytorch的,看代码发现总是存在torchkeras这个库,如果这个库只是为了查看各层参数之类的.可以将其作为插件介绍一番,没必要篇篇文章都加入,感觉有点不太好.本来就是起步学习,真诚希望代码越简洁越好.

**Comment by Jackiexiao** [comment]
我的个人看法是：
* 挺多时候只用到了summary功能（展示网络更为直观）
* torchkeras代码比较简单，不到三百行，很容易理解

**Comment by ziliangok** [comment]
它用来展示比较直观。我个人都是跳着看的，像第四，五，六章的内容和第三章的内容差不多。
